### PR TITLE
Update links to release asset files

### PR DESCRIPTION
**Pull request by pavelkornev**
- update links to zip files (now they point to GitHub releases)
- add link to DemoKit for each release

### CODE REVIEW

**Comment by pavelkornev** [comment]
Live — https://pavelkornev.github.io/openui5-website/update_release_links/releases/

**Comment by akudev** [comment]
Is the automated upload permanently activated now? And the release team aware that they do not need to include the zips into the war anymore?
+2

**Comment by pavelkornev** [comment]
@akudev this what our sync on May 7th is about..

**Comment by akudev** [comment]
Sure, but if both my questions are answered with "no", then someone may accidentally only update the version numbers in the website after the next WAR deployment and then we would have 404 links.

**Pull request merged**
